### ISSUE TITLE
How can I navigate between weeks/months/year ?

### ISSUE THREAD

**Issue by binhhong1412** [mikezzb/react-native-timetable#2]
Your timetable is the most beautiful one I've been finding out there and best suits my need (Time Schedule for School). However I don't see any property supporting week navigation. And I don't see one in the Usage.

Please show me or add this function if you haven't built. Thank you very much.

**Comment by mikezzb** [comment]
Thanks for your support!

As this timetable component is designed for a repetitive schedule (i.e. same schedule for every week), no week navigation is supported.

If you want to add calendar-based events, you may use react-native-calendars to select a date and recompute the events for that week, you may also want to hide the header & tick (will provide options in the next release) to update the dates for that week.

**Comment by HelianDevalios** [comment]
Thanks for your response. Because other calendar doesn’t show the info of the event card by default (which needs pressing to show) so I chose yours. 
Also my idea is that there are subjects which ends sooner or starts on next weeks so I think Week navigation helps students see the Schedule better and prepare well.

Did you mean to import their calendar while using your library to use their Week navigation along with your Time table ?

I am new to React native so I now can only rely on libraries. Therefore I don’t know if we can combine functions from different libraries and they don’t conflict. If you accept to build the navigation (Back & forth), it’d be a Great help and an ultimate react-native-timetable out there 🤣. Thanks again.

**Comment by mikezzb** [comment]
I understand that you wish to build a timetable with distinct events every week, and navigate between weeks.

I agree that it will be great for this component to support it. Nevertheless, it requires a substantial change in logic and API of this component, and I am sorry that I do not have the time to do it in the foreseeable time.

You may fork this component to build your own logic on top of the event card UI. Gook luck with your project!

**Comment by HelianDevalios** [comment]
Okay, I see. Thanks for spending your time!
